version: "3"
services:
  backend:
    image: tm-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "3001:3001"

  frontend:
    image: tm-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
  
